/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.freshfoods;

/**
 *
 * @author biana
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        bgAccFrame = new javax.swing.JPanel();
        header1 = new javax.swing.JLabel();
        emptylabeldesign = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginButtoncustomer = new javax.swing.JButton();
        signUpButtoncustomer = new javax.swing.JButton();
        userlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        userlabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        signUpAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(46, 40, 42));
        header.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        header.setForeground(new java.awt.Color(118, 176, 65));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("FreshFoods");
        header.setOpaque(true);

        bgAccFrame.setBackground(new java.awt.Color(247, 249, 247));
        bgAccFrame.setPreferredSize(new java.awt.Dimension(720, 720));
        bgAccFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(46, 40, 42));
        header1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        header1.setForeground(new java.awt.Color(118, 176, 65));
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("FreshFoods");
        header1.setOpaque(true);
        bgAccFrame.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 90));

        emptylabeldesign.setBackground(new java.awt.Color(118, 176, 65));
        emptylabeldesign.setForeground(new java.awt.Color(118, 176, 65));
        emptylabeldesign.setText("                                    ");
        emptylabeldesign.setOpaque(true);
        bgAccFrame.add(emptylabeldesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 720, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        loginButtoncustomer.setBackground(new java.awt.Color(118, 176, 65));
        loginButtoncustomer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        loginButtoncustomer.setText("login");
        loginButtoncustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginButtoncustomer.setBorderPainted(false);
        loginButtoncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtoncustomerActionPerformed(evt);
            }
        });

        signUpButtoncustomer.setBackground(new java.awt.Color(118, 176, 65));
        signUpButtoncustomer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        signUpButtoncustomer.setText("signup");
        signUpButtoncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtoncustomerActionPerformed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userlabel.setForeground(new java.awt.Color(102, 102, 102));
        userlabel.setText("Login as an admin");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME");

        admin.setBackground(new java.awt.Color(118, 176, 65));
        admin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        admin.setText("login");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        userlabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userlabel1.setForeground(new java.awt.Color(102, 102, 102));
        userlabel1.setText("Login as a customer");

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        signUpAdmin.setBackground(new java.awt.Color(118, 176, 65));
        signUpAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        signUpAdmin.setText("signup");
        signUpAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(userlabel)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(admin)
                                .addGap(18, 18, 18)
                                .addComponent(signUpAdmin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginButtoncustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpButtoncustomer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel)
                    .addComponent(admin)
                    .addComponent(signUpAdmin))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButtoncustomer)
                    .addComponent(signUpButtoncustomer)
                    .addComponent(userlabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        bgAccFrame.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 360, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgAccFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 630, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgAccFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtoncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtoncustomerActionPerformed
        // TODO add your handling code here
        setVisible(false);
        new Userlogin().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_loginButtoncustomerActionPerformed

    private void signUpButtoncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtoncustomerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new signUp().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_signUpButtoncustomerActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:

        new adminLogin().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signUpAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpAdminActionPerformed
        // TODO add your handling code here:
        new adminsignup().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signUpAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
                accounts.createAccounts();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JPanel bgAccFrame;
    private javax.swing.JLabel emptylabeldesign;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButtoncustomer;
    private javax.swing.JButton signUpAdmin;
    private javax.swing.JButton signUpButtoncustomer;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel userlabel1;
    // End of variables declaration//GEN-END:variables
}
